repos:
  -   repo: https://github.com/asottile/seed-isort-config
      rev: v2.2.0
      hooks:
      - id: seed-isort-config
  -   repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.8.0
      hooks:
      - id: isort
  -   repo: https://github.com/grantjenks/blue
      rev: v0.8.0
      hooks:
      - id: blue
  -   repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
      - id: flake8
