name: Deploying app to Heroku

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.ADMIN_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./config/docker/
          dockerfile_name: backend.dockerfile
          docker_options: "--no-cache"
          process_type: web

      - name: Apllying migrations
        run: heroku run -x python manage.py migrate

      - name: Collecting static files
        run: heroku run -x SECRET_KEY=${{ secrets.SECRET_KEY }} python manage.py collectstatic --noinput
