name: Run integration tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build image
      run: make docker-build

    - name: Run integration tests
      run: make integration-tests
