name: Run integration tests

on:
  pull_request:
    branches: [ main ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
      - uses: actions/checkout@v2

      - name: Build image
        run: make docker-build

      - name: Run integration tests
        run: make interaction-tests
